import { useState, useEffect, useRef } from "react";
const ADMIN_PW="FAFT2026!admin",SEC_PIN="7743",MEMBER_PW="truck2026";
const G=`
@import url('https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300;0,9..144,400;0,9..144,500;1,9..144,300;1,9..144,400&family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');
:root{--bg:#FAFAF8;--card:#FFFFFF;--ink:#1A1613;--sub:#6B6560;--mute:#9C9690;--line:#E8E4DF;--tint:#F4F1ED;--accent:#D4482C;--accentL:#FFF0ED;--sans:'Inter',system-ui,sans-serif;--serif:'Fraunces',Georgia,serif;--mono:'JetBrains Mono',monospace}
*{box-sizing:border-box;margin:0;padding:0}body{-webkit-font-smoothing:antialiased;overflow-x:hidden;font-family:var(--sans);color:var(--ink);background:var(--bg)}
::selection{background:var(--accentL);color:var(--accent)}button{cursor:pointer;border:none;background:none;font-family:inherit;color:inherit}
input,textarea,select{font-family:var(--sans);outline:none}input:focus,textarea:focus,select:focus{border-color:var(--accent)!important}
a{text-decoration:none;color:inherit}
@keyframes up{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}
@keyframes ticker{0%{transform:translateX(0)}100%{transform:translateX(-33.33%)}}
.au{animation:up .6s cubic-bezier(.4,0,.2,1) both}.d1{animation-delay:.06s}.d2{animation-delay:.12s}.d3{animation-delay:.18s}.d4{animation-delay:.24s}
@media(max-width:768px){.g2,.g3{grid-template-columns:1fr!important}.hero-h{font-size:38px!important}.nav-links{display:none!important}.foot-grid{grid-template-columns:1fr 1fr!important}.form-2col{grid-template-columns:1fr!important}.stat-row{flex-direction:column!important;gap:32px!important}.mob-hide{display:none!important}}
`;
function useRouter(){const[r,setR]=useState(window.location.hash.slice(1)||"/");useEffect(()=>{const h=()=>{setR(window.location.hash.slice(1)||"/");window.scrollTo({top:0})};window.addEventListener("hashchange",h);return()=>window.removeEventListener("hashchange",h)},[]);return{route:r,go:p=>window.location.hash=p}}
function Btn({children,onClick,v="primary",full,sz="md",style={}}){const base={fontFamily:"var(--sans)",fontWeight:500,borderRadius:8,transition:"all .2s",display:"inline-flex",alignItems:"center",justifyContent:"center",letterSpacing:"-.01em"};const sizes={sm:{fontSize:13,padding:"10px 20px"},md:{fontSize:14,padding:"12px 24px"},lg:{fontSize:15,padding:"14px 32px"}};const variants={primary:{background:"var(--ink)",color:"#fff",...base,...sizes[sz]},accent:{background:"var(--accent)",color:"#fff",...base,...sizes[sz]},secondary:{background:"var(--tint)",color:"var(--ink)",border:"1px solid var(--line)",...base,...sizes[sz]},ghost:{background:"transparent",color:"var(--sub)",border:"1px solid var(--line)",...base,...sizes[sz]}};return<button onClick={onClick} style={{...variants[v],width:full?"100%":undefined,...style}} onMouseEnter={e=>{if(v==="primary")e.currentTarget.style.background="#333";else if(v==="accent")e.currentTarget.style.background="#B83A20";else e.currentTarget.style.borderColor="var(--mute)"}} onMouseLeave={e=>{if(v==="primary")e.currentTarget.style.background="var(--ink)";else if(v==="accent")e.currentTarget.style.background="var(--accent)";else e.currentTarget.style.borderColor="var(--line)"}}>{children}</button>}
function Input({label,value,onChange,placeholder,type="text",textarea,rows=3}){const s={width:"100%",padding:textarea?"14px 16px":"12px 16px",borderRadius:8,border:"1px solid var(--line)",fontSize:14,fontFamily:"var(--sans)",color:"var(--ink)",background:"var(--card)",marginBottom:16,resize:textarea?"vertical":"none"};return<div>{label&&<label style={{display:"block",fontSize:12,fontWeight:500,color:"var(--sub)",marginBottom:6,letterSpacing:".02em"}}>{label}</label>}{textarea?<textarea value={value} onChange={onChange} placeholder={placeholder} style={s} rows={rows}/>:<input value={value} onChange={onChange} placeholder={placeholder} type={type} style={s}/>}</div>}
function Nav({go,route}){return<nav style={{position:"fixed",top:0,left:0,right:0,zIndex:100,background:"rgba(250,250,248,.9)",backdropFilter:"blur(16px)",borderBottom:"1px solid var(--line)"}}><div style={{maxWidth:1120,margin:"0 auto",padding:"0 40px",height:56,display:"flex",alignItems:"center",justifyContent:"space-between"}}><div onClick={()=>go("/")} style={{cursor:"pointer",display:"flex",alignItems:"baseline",gap:6}}><span style={{fontFamily:"var(--serif)",fontSize:17,fontWeight:400,color:"var(--ink)",fontStyle:"italic"}}>find a</span><span style={{fontFamily:"var(--serif)",fontSize:17,fontWeight:500,color:"var(--accent)"}}>food truck</span></div><div className="nav-links" style={{display:"flex",alignItems:"center",gap:32}}>{[["Submit Event","/submit"],["Join as Vendor","/join"],["Verified Access","/access"]].map(([l,p])=><span key={p} onClick={()=>go(p)} style={{fontSize:13,fontWeight:500,color:route===p?"var(--ink)":"var(--mute)",cursor:"pointer",transition:"color .15s"}} onMouseEnter={e=>e.currentTarget.style.color="var(--ink)"} onMouseLeave={e=>{if(route!==p)e.currentTarget.style.color="var(--mute)"}}>{l}</span>)}</div><div style={{display:"flex",gap:8}}><Btn v="ghost" sz="sm" onClick={()=>go("/member")}>Vendor Login</Btn><Btn v="accent" sz="sm" onClick={()=>go("/submit")}>Submit Event</Btn></div></div></nav>}

function HomePage({go}){
  return<>
  {/* Hero */}
  <section style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",padding:"120px 40px 80px",position:"relative"}}>
    <div style={{position:"absolute",top:"10%",right:"8%",width:400,height:400,borderRadius:"50%",background:"radial-gradient(circle,rgba(212,72,44,.04),transparent 70%)",filter:"blur(40px)"}} className="mob-hide"/>
    <div style={{position:"absolute",bottom:"12%",left:"5%",width:300,height:300,borderRadius:"50%",background:"radial-gradient(circle,rgba(212,160,44,.03),transparent 70%)",filter:"blur(40px)"}} className="mob-hide"/>
    <div style={{maxWidth:680,textAlign:"center",position:"relative"}}>
      <div className="au" style={{marginBottom:48}}>
        <p style={{fontSize:12,fontWeight:500,color:"var(--mute)",letterSpacing:".08em",marginBottom:20}}>RICHMOND, VIRGINIA</p>
        <h1 className="hero-h" style={{fontSize:52,fontWeight:300,color:"var(--ink)",fontFamily:"var(--serif)",lineHeight:1.15,letterSpacing:"-.02em",margin:"0 0 24px"}}>The food truck booking<br/>network for <em style={{fontWeight:400,color:"var(--accent)"}}>Richmond</em>.</h1>
        <p style={{fontSize:17,color:"var(--sub)",lineHeight:1.7,maxWidth:460,margin:"0 auto",fontWeight:300}}>Submit event requests. Get matched with verified vendors. Book directly — no middlemen, no spam.</p>
      </div>
      <div className="au d1" style={{display:"flex",gap:12,justifyContent:"center"}}><Btn v="accent" sz="lg" onClick={()=>go("/submit")}>Submit an Event</Btn><Btn v="secondary" sz="lg" onClick={()=>go("/join")}>Join as a Vendor</Btn></div>
      <p className="au d2" style={{fontSize:12,color:"var(--mute)",marginTop:24,fontStyle:"italic",fontFamily:"var(--serif)"}}>Serving corporate events, weddings, festivals, and everything in between.</p>
    </div>
  </section>

  {/* Cuisine ticker */}
  <div style={{borderTop:"1px solid var(--line)",borderBottom:"1px solid var(--line)",padding:"14px 0",overflow:"hidden"}}><div style={{display:"flex",animation:"ticker 30s linear infinite",whiteSpace:"nowrap"}}>
    {[...Array(3)].map((_,j)=><div key={j} style={{display:"flex"}}>{["BBQ & Smoked Meats","Mexican / Latin","Southern / Soul Food","Asian Fusion","Breakfast & Brunch","Beverages & Dessert","Catering","Weddings","Corporate Events","Festivals"].map((t,i)=><span key={i} style={{padding:"0 32px",fontSize:12,color:"var(--mute)",fontFamily:"var(--mono)",letterSpacing:".02em"}}>{t}</span>)}</div>)}
  </div></div>

  {/* Hero image */}
  <div style={{padding:"48px 40px 0"}}><div style={{maxWidth:1040,margin:"0 auto",height:320,borderRadius:14,overflow:"hidden",position:"relative",background:"var(--ink)"}}>
    <img src="https://images.unsplash.com/photo-1565123409695-7b5ef63a2efb?w=1200&h=600&fit=crop" alt="Food trucks" style={{width:"100%",height:"100%",objectFit:"cover",display:"block",opacity:.55,filter:"saturate(.8)"}}/>
    <div style={{position:"absolute",inset:0,background:"linear-gradient(to right,rgba(26,22,19,.7) 0%,transparent 60%)"}}/>
    <div style={{position:"absolute",bottom:36,left:40}}>
      <p style={{fontSize:11,fontWeight:500,color:"rgba(255,255,255,.4)",letterSpacing:".08em",fontFamily:"var(--mono)",marginBottom:6}}>RICHMOND, VA</p>
      <p style={{fontSize:20,fontWeight:300,color:"#fff",fontFamily:"var(--serif)",lineHeight:1.4}}>Where the best trucks<br/>meet the best events.</p>
    </div>
  </div></div>

  {/* How It Works */}
  <section style={{padding:"80px 40px 100px"}}><div style={{maxWidth:1040,margin:"0 auto"}}>
    <div className="au" style={{marginBottom:56}}><p style={{fontSize:12,fontWeight:500,color:"var(--mute)",letterSpacing:".08em",marginBottom:12}}>HOW IT WORKS</p><h2 style={{fontSize:34,fontWeight:300,fontFamily:"var(--serif)",color:"var(--ink)",maxWidth:440,letterSpacing:"-.01em"}}>Simple for hosts.<br/>Valuable for vendors.</h2></div>
    <div className="au d1 g3" style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:1,background:"var(--line)",borderRadius:12,overflow:"hidden"}}>
      {[["For Event Hosts","Tell us your date, location, headcount, and requirements. We route your request to verified vendors who match — they respond directly with availability and pricing.","Submit an Event →","/submit"],["For Vendors","Get listed in the network for free. Receive qualified booking opportunities from hosts across Richmond. Upgrade to Verified for priority access and category protection.","Join the Network →","/join"],["Direct Booking","No platform fees. No middlemen. Hosts and vendors work out the details directly. We just make the connection.","Learn More →","/access"]].map(([t,d,cta,link])=><div key={t} style={{background:"var(--card)",padding:40}}><h3 style={{fontSize:14,fontWeight:600,color:"var(--ink)",marginBottom:12}}>{t}</h3><p style={{fontSize:14,color:"var(--sub)",lineHeight:1.75,marginBottom:24,fontWeight:300}}>{d}</p><span onClick={()=>go(link)} style={{fontSize:13,fontWeight:500,color:"var(--accent)",cursor:"pointer"}}>{cta}</span></div>)}
    </div>
  </div></section>

  {/* Decorative divider */}
  <div style={{padding:"0 40px"}}><div style={{maxWidth:1040,margin:"0 auto",display:"flex",alignItems:"center",gap:16}}><div style={{flex:1,height:1,background:"var(--line)"}}/><span style={{fontSize:11,color:"var(--mute)",fontFamily:"var(--mono)",letterSpacing:".1em",flexShrink:0}}>FAFTRVA</span><div style={{flex:1,height:1,background:"var(--line)"}}/></div></div>

  {/* Status */}
  <section style={{padding:"72px 40px"}}><div className="stat-row" style={{maxWidth:880,margin:"0 auto",display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}>
    <div className="au"><p style={{fontSize:12,fontWeight:500,color:"var(--mute)",letterSpacing:".08em",marginBottom:12}}>CURRENT STATUS</p><h2 style={{fontSize:28,fontWeight:300,fontFamily:"var(--serif)",color:"var(--ink)"}}>Now accepting</h2></div>
    <div className="au d1" style={{display:"flex",gap:44}}>{[["Event\nsubmissions","Active"],["Vendor\napplications","Active"],["Verified Vendor\nwaitlist","Open"]].map(([l,s])=><div key={l} style={{textAlign:"right"}}><div style={{display:"flex",alignItems:"center",gap:6,justifyContent:"flex-end",marginBottom:6}}><div style={{width:6,height:6,borderRadius:99,background:s==="Active"?"#2D8C3C":"var(--accent)"}}/><span style={{fontSize:11,fontWeight:500,color:s==="Active"?"#2D8C3C":"var(--accent)",fontFamily:"var(--mono)"}}>{s}</span></div><span style={{fontSize:13,color:"var(--sub)",whiteSpace:"pre-line",lineHeight:1.5}}>{l}</span></div>)}</div>
  </div></section>

  {/* Verified Access preview — dark section for contrast */}
  <section style={{padding:"100px 40px",background:"var(--ink)",position:"relative",overflow:"hidden"}}>
    <div style={{position:"absolute",top:"-20%",right:"-5%",width:400,height:400,borderRadius:"50%",background:"radial-gradient(circle,rgba(212,72,44,.06),transparent 60%)",filter:"blur(50px)"}}/>
    <div style={{maxWidth:600,margin:"0 auto",textAlign:"center",position:"relative"}}>
      <p className="au" style={{fontSize:12,fontWeight:500,color:"rgba(255,255,255,.3)",letterSpacing:".08em",marginBottom:16}}>VERIFIED VENDOR ACCESS</p>
      <h2 className="au d1" style={{fontSize:30,fontWeight:300,fontFamily:"var(--serif)",color:"#fff",margin:"0 0 20px",letterSpacing:"-.01em"}}>Priority placement. Direct lead access.<br/>Category protection.</h2>
      <p className="au d2" style={{fontSize:15,color:"rgba(255,255,255,.4)",lineHeight:1.75,marginBottom:16,fontWeight:300}}>A paid tier for vendors who want first access to booking requests, protected category placement, and featured visibility across the network.</p>
      <p className="au d2" style={{fontSize:14,color:"rgba(255,255,255,.3)",lineHeight:1.7,marginBottom:36,fontWeight:300,fontStyle:"italic",fontFamily:"var(--serif)"}}>Limited to 1–2 vendors per cuisine category. When your slot is full, your competition is capped.</p>
      <div className="au d3"><Btn v="accent" sz="lg" onClick={()=>go("/access")}>Join the Waitlist</Btn></div>
    </div>
  </section>

  {/* Warm close */}
  <section style={{padding:"80px 40px",textAlign:"center"}}>
    <div style={{maxWidth:520,margin:"0 auto"}}>
      <h2 className="au" style={{fontSize:28,fontWeight:300,fontFamily:"var(--serif)",color:"var(--ink)",margin:"0 0 16px"}}>Richmond's food truck scene deserves better infrastructure.</h2>
      <p className="au d1" style={{fontSize:15,color:"var(--sub)",lineHeight:1.75,fontWeight:300,marginBottom:32}}>We're building it. Get in early — whether you're hosting an event or running a truck.</p>
      <div className="au d2" style={{display:"flex",gap:12,justifyContent:"center"}}><Btn v="accent" onClick={()=>go("/submit")}>Submit an Event</Btn><Btn v="secondary" onClick={()=>go("/join")}>Join as a Vendor</Btn></div>
    </div>
  </section>

  {/* Quiet numbers */}
  <section style={{padding:"72px 40px",borderTop:"1px solid var(--line)"}}><div style={{maxWidth:800,margin:"0 auto",display:"flex",justifyContent:"center",gap:64}}>
    {[["4,100+","Network members"],["$800–2,500","Avg. booking value"],["10","Verified vendor slots"]].map(([v,l])=><div key={l} style={{textAlign:"center"}}><div style={{fontSize:32,fontWeight:300,color:"var(--ink)",fontFamily:"var(--serif)",letterSpacing:"-.02em"}}>{v}</div><div style={{fontSize:11,color:"var(--mute)",marginTop:6,fontFamily:"var(--mono)",letterSpacing:".04em"}}>{l}</div></div>)}
  </div></section>
</>}
function SubmitEvent({go}){
  const[step,setStep]=useState(1);const[form,setForm]=useState({type:"",date:"",time:"",location:"",attendance:"",cuisine:"",budget:"",name:"",email:"",phone:"",org:"",notes:""});const u=(k,v)=>setForm({...form,[k]:v});
  const types=["Corporate","Wedding","Private Party","Festival","Community","School / Nonprofit","Other"];
  const Chip=({children,active,onClick})=><button onClick={onClick} style={{padding:"8px 16px",borderRadius:8,fontSize:13,fontWeight:500,border:"1px solid",borderColor:active?"var(--accent)":"var(--line)",background:active?"var(--accent)":"var(--card)",color:active?"#fff":"var(--sub)",transition:"all .15s"}}>{children}</button>;
  if(step===4)return<section style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",padding:"120px 40px"}}><div className="au" style={{textAlign:"center",maxWidth:440}}><div style={{width:48,height:48,borderRadius:99,background:"var(--accent)",color:"#fff",display:"flex",alignItems:"center",justifyContent:"center",fontSize:20,margin:"0 auto 24px"}}>✓</div><h2 style={{fontSize:28,fontWeight:300,fontFamily:"var(--serif)",margin:"0 0 12px"}}>Request submitted.</h2><p style={{fontSize:15,color:"var(--sub)",lineHeight:1.7,fontWeight:300}}>Verified vendors matching your requirements will be notified. Expect responses within 24 hours.</p><div style={{marginTop:32}}><Btn v="secondary" onClick={()=>go("/")}>Back to home</Btn></div></div></section>;
  return<section style={{minHeight:"100vh",padding:"120px 40px 80px"}}><div style={{maxWidth:560,margin:"0 auto"}}>
    <div className="au" style={{marginBottom:40}}><span onClick={()=>go("/")} style={{fontSize:13,color:"var(--mute)",cursor:"pointer",marginBottom:16,display:"inline-block"}}>← Back</span><h1 style={{fontSize:30,fontWeight:300,fontFamily:"var(--serif)",margin:"0 0 8px"}}>Submit an Event</h1><p style={{fontSize:14,color:"var(--sub)",fontWeight:300}}>Step {step} of 3</p></div>
    <div style={{display:"flex",gap:4,marginBottom:40}}>{[1,2,3].map(s=><div key={s} style={{flex:1,height:2,borderRadius:2,background:s<=step?"var(--accent)":"var(--line)",transition:"background .3s"}}/>)}</div>
    <div className="au d1" style={{background:"var(--card)",borderRadius:12,border:"1px solid var(--line)",padding:40}}>
      {step===1&&<><h3 style={{fontSize:16,fontWeight:600,marginBottom:24}}>Event Details</h3><div style={{marginBottom:20}}><label style={{display:"block",fontSize:12,fontWeight:500,color:"var(--sub)",marginBottom:8}}>Event Type</label><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{types.map(t=><Chip key={t} active={form.type===t} onClick={()=>u("type",t)}>{t}</Chip>)}</div></div><div className="form-2col" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"0 16px"}}><Input label="Date" value={form.date} onChange={e=>u("date",e.target.value)} type="date"/><Input label="Time" value={form.time} onChange={e=>u("time",e.target.value)} placeholder="e.g. 4:00 PM – 8:00 PM"/></div><Input label="Location" value={form.location} onChange={e=>u("location",e.target.value)} placeholder="Venue name or address"/><Input label="Expected Attendance" value={form.attendance} onChange={e=>u("attendance",e.target.value)} placeholder="Number of guests" type="number"/><div style={{display:"flex",justifyContent:"flex-end",marginTop:8}}><Btn v="accent" onClick={()=>setStep(2)}>Continue</Btn></div></>}
      {step===2&&<><h3 style={{fontSize:16,fontWeight:600,marginBottom:24}}>Requirements</h3><Input label="Cuisine Preferences" value={form.cuisine} onChange={e=>u("cuisine",e.target.value)} placeholder="e.g. BBQ, Mexican, Any"/><Input label="Budget Range" value={form.budget} onChange={e=>u("budget",e.target.value)} placeholder="e.g. $500 – $1,000"/><Input label="Additional Requirements" value={form.notes} onChange={e=>u("notes",e.target.value)} placeholder="Dietary needs, setup requirements, number of trucks..." textarea rows={4}/><div style={{display:"flex",justifyContent:"space-between",marginTop:8}}><Btn v="ghost" onClick={()=>setStep(1)}>Back</Btn><Btn v="accent" onClick={()=>setStep(3)}>Continue</Btn></div></>}
      {step===3&&<><h3 style={{fontSize:16,fontWeight:600,marginBottom:24}}>Contact Information</h3><Input label="Your Name" value={form.name} onChange={e=>u("name",e.target.value)} placeholder="Full name"/><Input label="Organization" value={form.org} onChange={e=>u("org",e.target.value)} placeholder="Company or organization (optional)"/><div className="form-2col" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"0 16px"}}><Input label="Email" value={form.email} onChange={e=>u("email",e.target.value)} placeholder="you@email.com" type="email"/><Input label="Phone" value={form.phone} onChange={e=>u("phone",e.target.value)} placeholder="(804) 555-0000"/></div><div style={{display:"flex",justifyContent:"space-between",marginTop:8}}><Btn v="ghost" onClick={()=>setStep(2)}>Back</Btn><Btn v="accent" onClick={()=>setStep(4)}>Submit Request</Btn></div></>}
    </div>
  </div></section>;
}

function JoinVendor({go}){
  const[step,setStep]=useState(1);const[form,setForm]=useState({truck:"",cuisine:"",owner:"",phone:"",email:"",schedule:"",description:"",waitlist:false});const u=(k,v)=>setForm({...form,[k]:v});
  const cuisines=["BBQ & Smoked","Mexican / Latin","Southern / Soul","Asian Fusion","Breakfast / Brunch","Beverages / Dessert","Other"];
  const Chip=({children,active,onClick})=><button onClick={onClick} style={{padding:"8px 14px",borderRadius:8,fontSize:12,fontWeight:500,border:"1px solid",borderColor:active?"var(--accent)":"var(--line)",background:active?"var(--accent)":"var(--card)",color:active?"#fff":"var(--sub)",transition:"all .15s"}}>{children}</button>;
  if(step===4)return<section style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",padding:"120px 40px"}}><div className="au" style={{textAlign:"center",maxWidth:440}}><div style={{width:48,height:48,borderRadius:99,background:"var(--accent)",color:"#fff",display:"flex",alignItems:"center",justifyContent:"center",fontSize:20,margin:"0 auto 24px"}}>✓</div><h2 style={{fontSize:28,fontWeight:300,fontFamily:"var(--serif)",margin:"0 0 12px"}}>You're in the network.</h2><p style={{fontSize:15,color:"var(--sub)",lineHeight:1.7,fontWeight:300,marginBottom:8}}>Your application is received. Log in to complete your profile and add your menu.</p>{form.waitlist&&<p style={{fontSize:13,fontWeight:500,background:"var(--accentL)",color:"var(--accent)",padding:"10px 16px",borderRadius:8,display:"inline-block",marginTop:12}}>Verified Vendor waitlist — application received.</p>}<div style={{marginTop:32,display:"flex",gap:10,justifyContent:"center"}}><Btn v="accent" onClick={()=>go("/member")}>Set Up Profile</Btn><Btn v="secondary" onClick={()=>go("/")}>Back to home</Btn></div></div></section>;
  return<section style={{minHeight:"100vh",padding:"120px 40px 80px"}}><div style={{maxWidth:560,margin:"0 auto"}}>
    <div className="au" style={{marginBottom:40}}><span onClick={()=>go("/")} style={{fontSize:13,color:"var(--mute)",cursor:"pointer",marginBottom:16,display:"inline-block"}}>← Back</span><h1 style={{fontSize:30,fontWeight:300,fontFamily:"var(--serif)",margin:"0 0 8px"}}>Join as a Vendor</h1><p style={{fontSize:14,color:"var(--sub)",fontWeight:300}}>Step {step} of 3 — Free to join</p></div>
    <div style={{display:"flex",gap:4,marginBottom:40}}>{[1,2,3].map(s=><div key={s} style={{flex:1,height:2,borderRadius:2,background:s<=step?"var(--accent)":"var(--line)",transition:"background .3s"}}/>)}</div>
    <div className="au d1" style={{background:"var(--card)",borderRadius:12,border:"1px solid var(--line)",padding:40}}>
      {step===1&&<><h3 style={{fontSize:16,fontWeight:600,marginBottom:24}}>Business Information</h3><Input label="Truck Name" value={form.truck} onChange={e=>u("truck",e.target.value)} placeholder="Your food truck name"/><div style={{marginBottom:20}}><label style={{display:"block",fontSize:12,fontWeight:500,color:"var(--sub)",marginBottom:8}}>Primary Cuisine</label><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{cuisines.map(c=><Chip key={c} active={form.cuisine===c} onClick={()=>u("cuisine",c)}>{c}</Chip>)}</div></div><Input label="Typical Schedule" value={form.schedule} onChange={e=>u("schedule",e.target.value)} placeholder="e.g. Tue–Sat 11am–8pm"/><Input label="Brief Description" value={form.description} onChange={e=>u("description",e.target.value)} placeholder="What you serve, your style..." textarea rows={3}/><div style={{display:"flex",justifyContent:"flex-end",marginTop:8}}><Btn v="accent" onClick={()=>setStep(2)}>Continue</Btn></div></>}
      {step===2&&<><h3 style={{fontSize:16,fontWeight:600,marginBottom:24}}>Contact</h3><Input label="Owner / Operator Name" value={form.owner} onChange={e=>u("owner",e.target.value)} placeholder="Full name"/><div className="form-2col" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"0 16px"}}><Input label="Email" value={form.email} onChange={e=>u("email",e.target.value)} placeholder="you@email.com" type="email"/><Input label="Phone" value={form.phone} onChange={e=>u("phone",e.target.value)} placeholder="(804) 555-0000"/></div><div style={{display:"flex",justifyContent:"space-between",marginTop:8}}><Btn v="ghost" onClick={()=>setStep(1)}>Back</Btn><Btn v="accent" onClick={()=>setStep(3)}>Continue</Btn></div></>}
      {step===3&&<><h3 style={{fontSize:16,fontWeight:600,marginBottom:24}}>Verified Vendor Access</h3><div style={{background:"var(--tint)",borderRadius:10,padding:24,marginBottom:24,border:"1px solid var(--line)"}}><h4 style={{fontSize:14,fontWeight:600,marginBottom:8}}>Verified Vendor tier — launching soon</h4><p style={{fontSize:13,color:"var(--sub)",lineHeight:1.7,fontWeight:300,marginBottom:16}}>Priority placement, direct lead routing by cuisine, category protection, and featured visibility across the network.</p><label style={{display:"flex",alignItems:"flex-start",gap:10,cursor:"pointer"}}><input type="checkbox" checked={form.waitlist} onChange={e=>u("waitlist",e.target.checked)} style={{marginTop:3,accentColor:"var(--accent)"}}/><span style={{fontSize:13,color:"var(--ink)",lineHeight:1.6}}>Yes, add me to the Verified Vendor waitlist.</span></label></div><div style={{display:"flex",justifyContent:"space-between",marginTop:8}}><Btn v="ghost" onClick={()=>setStep(2)}>Back</Btn><Btn v="accent" onClick={()=>setStep(4)}>Join Network</Btn></div></>}
    </div>
  </div></section>;
}
function AccessPage({go}){
  const[applied,setApplied]=useState(false);const[form,setForm]=useState({name:"",truck:"",cuisine:"",email:"",why:""});const u=(k,v)=>setForm({...form,[k]:v});
  const cuisines=["BBQ & Smoked","Mexican / Latin","Southern / Soul","Asian Fusion","Breakfast / Brunch","Beverages / Dessert"];
  const Chip=({children,active,onClick})=><button onClick={onClick} style={{padding:"7px 14px",borderRadius:8,fontSize:12,fontWeight:500,border:"1px solid",borderColor:active?"var(--accent)":"var(--line)",background:active?"var(--accent)":"var(--card)",color:active?"#fff":"var(--sub)",transition:"all .15s"}}>{children}</button>;
  return<section style={{minHeight:"100vh",padding:"120px 40px 80px"}}><div style={{maxWidth:720,margin:"0 auto"}}>
    <div className="au" style={{marginBottom:56}}><span onClick={()=>go("/")} style={{fontSize:13,color:"var(--mute)",cursor:"pointer",marginBottom:16,display:"inline-block"}}>← Back</span><h1 style={{fontSize:34,fontWeight:300,fontFamily:"var(--serif)",margin:"0 0 16px",letterSpacing:"-.01em"}}>Verified Vendor Access</h1><p style={{fontSize:16,color:"var(--sub)",lineHeight:1.75,fontWeight:300,maxWidth:540}}>A structured tier for vendors who want priority access to booking requests, protected category placement, and featured visibility.</p></div>
    <div className="au d1 g2" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:1,background:"var(--line)",borderRadius:12,overflow:"hidden",marginBottom:56}}>
      {[["Priority Placement","Your profile and responses appear first to event hosts across the network."],["Direct Lead Routing","Booking requests matched to your cuisine category are sent directly to you."],["Category Protection","Limited slots per cuisine. When your category is full, no competing vendor can join."],["Featured Visibility","Prominent placement in the directory, search results, and event matching."]].map(([t,d])=><div key={t} style={{background:"var(--card)",padding:32}}><h3 style={{fontSize:14,fontWeight:600,marginBottom:8}}>{t}</h3><p style={{fontSize:13,color:"var(--sub)",lineHeight:1.7,fontWeight:300}}>{d}</p></div>)}
    </div>
    {!applied?<div className="au d2" style={{background:"var(--card)",borderRadius:12,border:"1px solid var(--line)",padding:40}}>
      <h3 style={{fontSize:18,fontWeight:400,fontFamily:"var(--serif)",marginBottom:8}}>Join the waitlist</h3>
      <p style={{fontSize:13,color:"var(--sub)",lineHeight:1.7,fontWeight:300,marginBottom:28}}>We're reviewing applications for the initial verified vendor cohort. Limited availability per cuisine category.</p>
      <div className="form-2col" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"0 16px"}}><Input label="Your Name" value={form.name} onChange={e=>u("name",e.target.value)} placeholder="Full name"/><Input label="Truck Name" value={form.truck} onChange={e=>u("truck",e.target.value)} placeholder="Your food truck"/></div>
      <Input label="Email" value={form.email} onChange={e=>u("email",e.target.value)} placeholder="you@email.com" type="email"/>
      <div style={{marginBottom:16}}><label style={{display:"block",fontSize:12,fontWeight:500,color:"var(--sub)",marginBottom:8}}>Cuisine Category</label><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{cuisines.map(c=><Chip key={c} active={form.cuisine===c} onClick={()=>u("cuisine",c)}>{c}</Chip>)}</div></div>
      <Input label="Why are you interested?" value={form.why} onChange={e=>u("why",e.target.value)} placeholder="Tell us about your truck..." textarea rows={3}/>
      <Btn v="accent" full onClick={()=>{if(form.name&&form.truck&&form.email&&form.cuisine)setApplied(true)}}>Submit Application</Btn>
    </div>
    :<div className="au" style={{textAlign:"center",padding:"60px 20px"}}><div style={{width:48,height:48,borderRadius:99,background:"var(--accent)",color:"#fff",display:"flex",alignItems:"center",justifyContent:"center",fontSize:20,margin:"0 auto 24px"}}>✓</div><h3 style={{fontSize:24,fontWeight:300,fontFamily:"var(--serif)",margin:"0 0 12px"}}>Application received.</h3><p style={{fontSize:15,color:"var(--sub)",lineHeight:1.7,fontWeight:300,maxWidth:400,margin:"0 auto"}}>We'll review your application and reach out when the verified tier launches.</p><div style={{marginTop:24,fontSize:13,color:"var(--mute)",fontFamily:"var(--mono)"}}>{form.truck} · {form.cuisine}</div></div>}
  </div></section>;
}
function MemberLogin({onLogin}){const[pw,setPw]=useState("");const[err,setErr]=useState(false);return<div style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center"}}><div className="au" style={{width:380,padding:40,borderRadius:12,background:"var(--card)",border:"1px solid var(--line)",textAlign:"center"}}><h2 style={{fontSize:22,fontWeight:300,fontFamily:"var(--serif)",margin:"0 0 6px"}}>Vendor Portal</h2><p style={{fontSize:13,color:"var(--sub)",marginBottom:28,fontWeight:300}}>Manage your profile and menu.</p>{err&&<p style={{color:"#DC2626",fontSize:12,marginBottom:12}}>Invalid password.</p>}<input value={pw} onChange={e=>setPw(e.target.value)} onKeyDown={e=>e.key==="Enter"&&(onLogin(pw)?0:(setErr(true),setPw("")))} type="password" placeholder="Enter password" style={{width:"100%",padding:"12px 16px",borderRadius:8,border:"1px solid var(--line)",fontSize:14,marginBottom:12,textAlign:"center"}}/><Btn v="accent" full onClick={()=>{if(!onLogin(pw)){setErr(true);setPw("")}}}>Sign In</Btn></div></div>}

function MemberDash({go}){
  const[tab,setTab]=useState("profile");const[profile,setProfile]=useState({name:"",cuisine:"",owner:"",phone:"",schedule:"",price:"",desc:""});const[menu,setMenu]=useState([]);const[newItem,setNewItem]=useState({name:"",price:"",desc:""});const[scanning,setScanning]=useState(false);const[scanError,setScanError]=useState(null);const[scanPreview,setScanPreview]=useState(null);const fileRef=useRef(null);const up=(k,v)=>setProfile({...profile,[k]:v});
  const handleMenuScan=async(file)=>{if(!file)return;setScanError(null);setScanning(true);const reader=new FileReader();reader.onload=async(ev)=>{const dataUrl=ev.target.result;setScanPreview(dataUrl);const base64=dataUrl.split(",")[1];const mediaType=file.type||"image/jpeg";try{const resp=await fetch("/api/scan-menu",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({base64,mediaType})});const data=await resp.json();if(data.error&&(!data.items||data.items.length===0)){setScanError(data.error)}else if(data.items&&data.items.length>0){setMenu(prev=>[...prev,...data.items])}else{setScanError("Couldn't parse menu items.")}}catch(e){setScanError("Failed to process. Try again.")}setScanning(false)};reader.readAsDataURL(file)};
  return<section style={{minHeight:"100vh",padding:"80px 40px 60px"}}><div style={{maxWidth:960,margin:"0 auto"}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:40}}><div><h1 style={{fontSize:24,fontWeight:400,fontFamily:"var(--serif)"}}>Vendor Dashboard</h1><p style={{fontSize:13,color:"var(--sub)",marginTop:4}}>Manage your profile, menu, and visibility.</p></div><Btn v="ghost" sz="sm" onClick={()=>go("/")}>← Site</Btn></div>
    <div style={{display:"flex",gap:4,marginBottom:32,borderBottom:"1px solid var(--line)"}}>{["profile","menu"].map(t=><button key={t} onClick={()=>setTab(t)} style={{padding:"12px 20px",fontSize:13,fontWeight:500,color:tab===t?"var(--ink)":"var(--mute)",borderBottom:tab===t?"2px solid var(--accent)":"2px solid transparent",textTransform:"capitalize"}}>{t}</button>)}</div>
    {tab==="profile"&&<div style={{background:"var(--card)",borderRadius:12,border:"1px solid var(--line)",padding:40,maxWidth:560}}><h3 style={{fontSize:16,fontWeight:600,marginBottom:24}}>Truck Profile</h3><Input label="Truck Name" value={profile.name} onChange={e=>up("name",e.target.value)} placeholder="Your truck name"/><div className="form-2col" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"0 16px"}}><Input label="Cuisine" value={profile.cuisine} onChange={e=>up("cuisine",e.target.value)} placeholder="e.g. BBQ"/><Input label="Price Range" value={profile.price} onChange={e=>up("price",e.target.value)} placeholder="e.g. $$"/></div><div className="form-2col" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"0 16px"}}><Input label="Owner" value={profile.owner} onChange={e=>up("owner",e.target.value)} placeholder="Your name"/><Input label="Phone" value={profile.phone} onChange={e=>up("phone",e.target.value)} placeholder="(804) 555-0000"/></div><Input label="Schedule" value={profile.schedule} onChange={e=>up("schedule",e.target.value)} placeholder="e.g. Tue–Sat 11am–8pm"/><Input label="Description" value={profile.desc} onChange={e=>up("desc",e.target.value)} placeholder="What makes your truck special..." textarea rows={3}/><Btn v="accent" full>Save Profile</Btn></div>}
    {tab==="menu"&&<div style={{maxWidth:640}}><h3 style={{fontSize:16,fontWeight:600,marginBottom:24}}>Menu ({menu.length} items)</h3>
      <div style={{background:"var(--card)",borderRadius:12,border:"1px dashed var(--line)",padding:32,textAlign:"center",marginBottom:24,cursor:"pointer"}} onClick={()=>fileRef.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)handleMenuScan(f)}}><input ref={fileRef} type="file" accept="image/*" style={{display:"none"}} onChange={e=>{const f=e.target.files[0];if(f)handleMenuScan(f)}}/>{scanning?<p style={{fontSize:13,color:"var(--sub)"}}>Scanning menu...</p>:<><p style={{fontSize:14,fontWeight:500,color:"var(--accent)",marginBottom:4}}>Scan menu from photo</p><p style={{fontSize:12,color:"var(--mute)"}}>Drop a photo or click to upload. AI reads it instantly.</p></>}</div>
      {scanPreview&&<div style={{marginBottom:16}}><img src={scanPreview} alt="Menu" style={{maxWidth:"100%",borderRadius:8,border:"1px solid var(--line)"}}/></div>}
      {scanError&&<p style={{color:"#DC2626",fontSize:12,marginBottom:16}}>{scanError}</p>}
      {menu.map((m,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"14px 0",borderBottom:"1px solid var(--line)"}}><div><div style={{fontSize:14,fontWeight:500}}>{m.name}</div>{m.desc&&<div style={{fontSize:12,color:"var(--mute)",marginTop:2}}>{m.desc}</div>}</div><div style={{display:"flex",alignItems:"center",gap:12}}><span style={{fontSize:14,fontWeight:600,fontFamily:"var(--mono)"}}>${m.price}</span><button onClick={()=>setMenu(menu.filter((_,j)=>j!==i))} style={{fontSize:12,color:"var(--mute)",padding:"4px 8px",borderRadius:6,border:"1px solid var(--line)"}}>Remove</button></div></div>)}
      <div style={{background:"var(--tint)",borderRadius:10,padding:20,marginTop:24}}><p style={{fontSize:12,fontWeight:500,color:"var(--sub)",marginBottom:12}}>ADD MANUALLY</p><div style={{display:"grid",gridTemplateColumns:"1fr 80px",gap:8,marginBottom:8}}><input value={newItem.name} onChange={e=>setNewItem({...newItem,name:e.target.value})} placeholder="Item name" style={{padding:"10px 12px",borderRadius:6,border:"1px solid var(--line)",fontSize:13}}/><input value={newItem.price} onChange={e=>setNewItem({...newItem,price:e.target.value})} placeholder="$" style={{padding:"10px 12px",borderRadius:6,border:"1px solid var(--line)",fontSize:13}}/></div><input value={newItem.desc} onChange={e=>setNewItem({...newItem,desc:e.target.value})} placeholder="Description (optional)" style={{width:"100%",padding:"10px 12px",borderRadius:6,border:"1px solid var(--line)",fontSize:13,marginBottom:10}}/><Btn v="accent" full sz="sm" onClick={()=>{if(newItem.name&&newItem.price){setMenu([...menu,{name:newItem.name,price:Number(newItem.price),desc:newItem.desc}]);setNewItem({name:"",price:"",desc:""})}}}>Add Item</Btn></div>
    </div>}
  </div></section>;
}
function AdminLogin({onLogin}){const[pw,setPw]=useState("");const[err,setErr]=useState(false);return<div style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",background:"#0A0A0A"}}><div className="au" style={{width:360,padding:40,borderRadius:12,background:"#141414",border:"1px solid #222",textAlign:"center"}}><h2 style={{fontSize:20,fontWeight:500,color:"#fff",marginBottom:24}}>Admin Access</h2>{err&&<p style={{color:"#EF4444",fontSize:12,marginBottom:12}}>Invalid.</p>}<input value={pw} onChange={e=>setPw(e.target.value)} onKeyDown={e=>e.key==="Enter"&&(onLogin(pw)?0:(setErr(true),setPw("")))} type="password" placeholder="Password" style={{width:"100%",padding:"12px 16px",borderRadius:8,border:"1px solid #333",fontSize:14,background:"#0A0A0A",color:"#fff",marginBottom:12,textAlign:"center"}}/><button onClick={()=>{if(!onLogin(pw)){setErr(true);setPw("")}}} style={{width:"100%",padding:12,borderRadius:8,background:"#fff",color:"#000",fontSize:14,fontWeight:500}}>Enter</button></div></div>}
function PinGate({onUnlock,onCancel}){const[pin,setPin]=useState("");const[err,setErr]=useState(false);return<div style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",background:"#0A0A0A"}}><div style={{width:320,textAlign:"center"}}><h2 style={{fontSize:18,fontWeight:500,color:"#fff",marginBottom:24}}>Security PIN</h2>{err&&<p style={{color:"#EF4444",fontSize:12,marginBottom:12}}>Invalid PIN.</p>}<input value={pin} onChange={e=>setPin(e.target.value)} onKeyDown={e=>e.key==="Enter"&&(pin===SEC_PIN?onUnlock():(setErr(true),setPin("")))} type="password" maxLength={4} placeholder="••••" style={{width:"100%",padding:14,borderRadius:8,border:"1px solid #333",fontSize:24,letterSpacing:12,background:"#0A0A0A",color:"#fff",textAlign:"center",marginBottom:16}}/><div style={{display:"flex",gap:8}}><button onClick={onCancel} style={{flex:1,padding:12,borderRadius:8,border:"1px solid #333",color:"#666",fontSize:13}}>Cancel</button><button onClick={()=>{pin===SEC_PIN?onUnlock():(setErr(true),setPin(""))}} style={{flex:1,padding:12,borderRadius:8,background:"#fff",color:"#000",fontSize:13,fontWeight:500}}>Unlock</button></div></div></div>}
function AdminDash({go}){return<div style={{minHeight:"100vh",background:"#0A0A0A",padding:40,color:"#fff"}}><div style={{maxWidth:960,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:40}}><h1 style={{fontSize:20,fontWeight:500}}>FAFTRVA Admin</h1><button onClick={()=>go("/")} style={{color:"#666",fontSize:13,border:"1px solid #333",padding:"8px 16px",borderRadius:8}}>← Site</button></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:16,marginBottom:40}}>{[["Event Submissions","0","Pending"],["Vendor Applications","0","Pending"],["Waitlist","0","Applications"]].map(([t,v,l])=><div key={t} style={{background:"#141414",borderRadius:10,padding:24,border:"1px solid #222"}}><div style={{fontSize:11,color:"#666",marginBottom:8,fontFamily:"var(--mono)"}}>{t}</div><div style={{fontSize:28,fontWeight:300}}>{v}</div><div style={{fontSize:11,color:"#444",marginTop:4}}>{l}</div></div>)}</div><p style={{color:"#444",fontSize:13}}>Dashboard populates as submissions arrive.</p></div></div>}
function Footer({go}){return<footer style={{borderTop:"1px solid var(--line)",padding:"48px 40px 32px"}}><div className="foot-grid" style={{maxWidth:1120,margin:"0 auto",display:"grid",gridTemplateColumns:"2fr 1fr 1fr 1fr",gap:40}}><div><div style={{display:"flex",alignItems:"baseline",gap:5}}><span style={{fontFamily:"var(--serif)",fontSize:16,fontStyle:"italic",color:"var(--ink)"}}>find a</span><span style={{fontFamily:"var(--serif)",fontSize:16,fontWeight:500,color:"var(--accent)"}}>food truck</span></div><p style={{fontSize:13,color:"var(--sub)",marginTop:8,lineHeight:1.7,fontWeight:300,maxWidth:260}}>Richmond's structured booking network for food trucks and event organizers.</p><p style={{fontSize:11,color:"var(--mute)",marginTop:12,fontFamily:"var(--mono)"}}>Built by Laurence Ash LLC</p></div>{[["Network",[["Submit Event","/submit"],["Join as Vendor","/join"],["Verified Access","/access"]]],["Account",[["Vendor Login","/member"],["Admin","/admin"]]],["Info",[["Contact","#"],["Terms","#"]]]].map(([t,items])=><div key={t}><h4 style={{fontSize:11,fontWeight:500,color:"var(--mute)",letterSpacing:".08em",marginBottom:14}}>{t.toUpperCase()}</h4>{items.map(([l,to])=><div key={l} onClick={()=>to.startsWith("/")?go(to):null} style={{color:"var(--sub)",fontSize:13,cursor:to.startsWith("/")?"pointer":"default",padding:"3px 0",fontWeight:300}} onMouseEnter={e=>e.currentTarget.style.color="var(--ink)"} onMouseLeave={e=>e.currentTarget.style.color="var(--sub)"}>{l}</div>)}</div>)}</div><div style={{maxWidth:1120,margin:"28px auto 0",paddingTop:16,borderTop:"1px solid var(--line)",display:"flex",justifyContent:"space-between"}}><span style={{color:"var(--mute)",fontSize:11,fontFamily:"var(--mono)"}}>© 2026 FAFTRVA</span><span style={{color:"var(--mute)",fontSize:11}}>Richmond, VA</span></div></footer>}
export default function App(){
  const{route,go}=useRouter();const[member,setMember]=useState(false);const[admin,setAdmin]=useState(false);const[pin,setPin]=useState(false);
  if(route==="/member"){if(!member)return<><style>{G}</style><MemberLogin onLogin={p=>{if(p===MEMBER_PW){setMember(true);return true}return false}}/></>;return<><style>{G}</style><MemberDash go={go}/></>}
  if(route==="/admin"){if(!admin)return<><style>{G}</style><AdminLogin onLogin={p=>{if(p===ADMIN_PW){setAdmin(true);setPin(false);return true}return false}}/></>;if(!pin)return<><style>{G}</style><PinGate onUnlock={()=>setPin(true)} onCancel={()=>{setAdmin(false);go("/")}}/></>;return<><style>{G}</style><AdminDash go={go}/></>}
  return<div style={{background:"var(--bg)",minHeight:"100vh"}}><style>{G}</style><Nav go={go} route={route}/>
    {route==="/"&&<><HomePage go={go}/><Footer go={go}/></>}
    {route==="/submit"&&<><SubmitEvent go={go}/><Footer go={go}/></>}
    {route==="/join"&&<><JoinVendor go={go}/><Footer go={go}/></>}
    {route==="/access"&&<><AccessPage go={go}/><Footer go={go}/></>}
  </div>;
}
