import { useState, useEffect, useRef } from "react";
const AP="FAFT2026!admin",SP="7743",MP="truck2026";
const Skyline=()=><svg viewBox="0 0 1200 200" fill="none" style={{position:"absolute",bottom:"-10px",left:"50%",transform:"translateX(-50%)",width:"120%",maxWidth:1400,opacity:.05,color:"var(--ink)",pointerEvents:"none"}}><path d={[
"M0 200 L0 180",
"L20 180 L20 170 L35 170 L35 160 L40 160 L40 130 L42 130 L42 110 L44 100 L44 85 L45 75 L46 65 L47 75 L48 85 L48 100 L50 110 L50 130 L52 130 L52 160 L60 160 L60 170 L75 170 L75 180",
"L95 180 L95 165 L105 165 L105 155 L115 155 L115 165 L125 165 L125 175 L135 175 L135 180",
"L155 180 L155 160 L165 160 L165 145 L170 145 L170 130 L175 130 L175 120 L180 120 L180 130 L185 130 L185 145 L195 145 L195 160 L205 160 L205 180",
"L215 180 L215 155 L220 155 L220 135 L225 135 L225 115 L228 115 L228 100 L230 100 L230 85 L233 85 L233 100 L235 100 L235 115 L240 115 L240 135 L245 135 L245 155 L250 155 L250 180",
"L255 180 L255 140 L258 140 L258 110 L260 110 L260 85 L263 85 L263 65 L265 65 L265 50 L267 50 L267 40 L270 40 L273 40 L273 50 L275 50 L275 65 L277 65 L277 85 L280 85 L280 110 L282 110 L282 140 L285 140 L285 180",
"L290 180 L290 145 L293 145 L293 115 L296 115 L296 90 L298 90 L298 70 L300 70 L300 55 L303 55 L303 35 L305 35 L305 25 L307 25 L307 35 L309 35 L309 55 L312 55 L312 70 L314 70 L314 90 L316 90 L316 115 L319 115 L319 145 L322 145 L322 180",
"L330 180 L330 150 L333 150 L333 120 L336 120 L336 95 L338 95 L338 75 L340 75 L340 60 L343 60 L343 75 L345 75 L345 95 L348 95 L348 120 L351 120 L351 150 L355 150 L355 180",
"L365 180 L365 155 L370 155 L370 135 L375 135 L375 155 L380 155 L380 170 L390 170 L390 180",
"L405 180 L405 165 L410 165 L410 150 L415 150 L415 140 L420 140 L420 130 L425 130 L425 120 L428 120 L428 110 L430 110 L430 105 L432 105 L432 100 L434 100 L434 90 L435 85 L436 80 L437 85 L438 90 L438 100 L440 100 L440 105 L442 105 L442 110 L444 110 L444 120 L447 120 L447 130 L452 130 L452 140 L457 140 L457 150 L462 150 L462 165 L467 165 L467 180",
"L485 180 L485 170 L500 170 L500 160 L515 160 L515 170 L530 170 L530 180",
"L545 180 L545 172 L548 168 L553 172 L553 180 L558 180 L558 172 L561 168 L566 172 L566 180 L571 180 L571 172 L574 168 L579 172 L579 180 L584 180 L584 172 L587 168 L592 172 L592 180",
"L610 180 L610 165 L620 165 L620 155 L625 155 L625 145 L630 145 L630 155 L635 155 L635 165 L645 165 L645 180",
"L665 180 L665 170 L675 170 L675 160 L678 160 L678 140 L680 140 L680 120 L682 120 L682 100 L683 90 L684 80 L685 70 L686 60 L687 70 L688 80 L689 90 L690 100 L690 120 L692 120 L692 140 L694 140 L694 160 L700 160 L700 170 L710 170 L710 180",
"L730 180 L730 170 L740 170 L740 165 L750 165 L750 170 L760 170 L760 180",
"L800 180 L800 175 L900 175 L900 180 L1000 180 L1000 185 L1200 185 L1200 200 L0 200 Z"
].join(" ")} stroke="currentColor" strokeWidth="1.2" fill="none"/></svg>;
const G=`
@import url('https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300;0,9..144,400;0,9..144,500;1,9..144,300;1,9..144,400&family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');
:root{--bg:#FAFAF8;--card:#FFFFFF;--ink:#1A1613;--sub:#6B6560;--mute:#9C9690;--line:#E8E4DF;--tint:#F4F1ED;--accent:#D4482C;--accentL:#FFF0ED;--sans:'Inter',system-ui,sans-serif;--serif:'Fraunces',Georgia,serif;--mono:'JetBrains Mono',monospace}
*{box-sizing:border-box;margin:0;padding:0}body{-webkit-font-smoothing:antialiased;overflow-x:hidden;font-family:var(--sans);color:var(--ink);background:var(--bg)}
::selection{background:var(--accentL);color:var(--accent)}button{cursor:pointer;border:none;background:none;font-family:inherit;color:inherit}
input,textarea,select{font-family:var(--sans);outline:none}input:focus,textarea:focus,select:focus{border-color:var(--accent)!important}
a{text-decoration:none;color:inherit}
@keyframes up{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}
@keyframes ticker{0%{transform:translateX(0)}100%{transform:translateX(-33.33%)}}
.au{animation:up .6s cubic-bezier(.4,0,.2,1) both}.d1{animation-delay:.08s}.d2{animation-delay:.16s}.d3{animation-delay:.24s}
.mobtn{display:none!important}
@media(max-width:768px){
.g3,.g2{grid-template-columns:1fr!important}
.hh{font-size:30px!important;line-height:1.25!important}
.dk{display:none!important}.mobtn{display:flex!important}
.fg{grid-template-columns:1fr!important;gap:32px!important}
.fc{grid-template-columns:1fr!important}
.sf{flex-direction:column!important;gap:16px!important;align-items:flex-start!important}
.sf .sf{flex-direction:row!important;flex-wrap:wrap!important;gap:24px!important}
.sf .sf>div{text-align:left!important}
.sf .sf>div>div{justify-content:flex-start!important}
.sp{padding-left:16px!important;padding-right:16px!important}
.hc{flex-direction:column!important;width:100%!important}.hc button{width:100%!important}
.nm{gap:20px!important}
.nm>div>div:first-child{font-size:24px!important}
.cp{padding:20px!important}
.hero-s{min-height:auto!important;padding-top:90px!important;padding-bottom:48px!important}
.sec-sm{padding-top:48px!important;padding-bottom:48px!important}
.sec-md{padding-top:56px!important;padding-bottom:56px!important}
.sub-t{font-size:14px!important}
.dark-s{padding-top:56px!important;padding-bottom:56px!important}
.h2m{font-size:24px!important}
}
`;
function useRouter(){const[r,setR]=useState(window.location.hash.slice(1)||"/");useEffect(()=>{const h=()=>{setR(window.location.hash.slice(1)||"/");window.scrollTo({top:0})};window.addEventListener("hashchange",h);return()=>window.removeEventListener("hashchange",h)},[]);return{route:r,go:p=>window.location.hash=p}}
function Btn({children,onClick,v="primary",full,sz="md"}){const b={fontFamily:"var(--sans)",fontWeight:500,borderRadius:8,transition:"all .2s",display:"inline-flex",alignItems:"center",justifyContent:"center",letterSpacing:"-.01em"};const zs={sm:{fontSize:13,padding:"10px 20px"},md:{fontSize:14,padding:"12px 24px"},lg:{fontSize:15,padding:"14px 32px"}};const vs={primary:{background:"var(--ink)",color:"#fff",...b,...zs[sz]},accent:{background:"var(--accent)",color:"#fff",...b,...zs[sz]},secondary:{background:"var(--tint)",color:"var(--ink)",border:"1px solid var(--line)",...b,...zs[sz]},ghost:{background:"transparent",color:"var(--sub)",border:"1px solid var(--line)",...b,...zs[sz]}};return<button onClick={onClick} style={{...vs[v],width:full?"100%":undefined}} onMouseEnter={e=>{if(v==="accent")e.currentTarget.style.background="#B83A20"}} onMouseLeave={e=>{if(v==="accent")e.currentTarget.style.background="var(--accent)"}}>{children}</button>}
function Input({label,value,onChange,placeholder,type="text",textarea,rows=3}){const s={width:"100%",padding:"12px 16px",borderRadius:8,border:"1px solid var(--line)",fontSize:14,fontFamily:"var(--sans)",color:"var(--ink)",background:"var(--card)",marginBottom:16,resize:textarea?"vertical":"none"};return<div>{label&&<label style={{display:"block",fontSize:12,fontWeight:500,color:"var(--sub)",marginBottom:6,letterSpacing:".02em"}}>{label}</label>}{textarea?<textarea value={value} onChange={onChange} placeholder={placeholder} style={s} rows={rows}/>:<input value={value} onChange={onChange} placeholder={placeholder} type={type} style={s}/>}</div>}
function Chip({children,active,onClick}){return<button onClick={onClick} style={{padding:"8px 14px",borderRadius:8,fontSize:12,fontWeight:500,border:"1px solid",borderColor:active?"var(--accent)":"var(--line)",background:active?"var(--accent)":"var(--card)",color:active?"#fff":"var(--sub)",transition:"all .15s"}}>{children}</button>}

function Nav({go,route}){const[o,setO]=useState(false);return<><nav style={{position:"fixed",top:0,left:0,right:0,zIndex:100,background:"rgba(250,250,248,.95)",backdropFilter:"blur(16px)",borderBottom:"1px solid var(--line)"}}><div style={{maxWidth:1120,margin:"0 auto",padding:"0 20px",height:56,display:"flex",alignItems:"center",justifyContent:"space-between"}}><div onClick={()=>{go("/");setO(false)}} style={{cursor:"pointer",display:"flex",alignItems:"baseline",gap:5}}><span style={{fontFamily:"var(--serif)",fontSize:17,fontWeight:400,fontStyle:"italic"}}>find a</span><span style={{fontFamily:"var(--serif)",fontSize:17,fontWeight:500,color:"var(--accent)"}}>food truck</span></div><div className="dk" style={{display:"flex",alignItems:"center",gap:32}}>{[["Submit Event","/submit"],["Join as Vendor","/join"],["Verified Access","/access"]].map(([l,p])=><span key={p} onClick={()=>go(p)} style={{fontSize:13,fontWeight:500,color:route===p?"var(--ink)":"var(--mute)",cursor:"pointer"}}>{l}</span>)}</div><div className="dk" style={{display:"flex",gap:8}}><Btn v="ghost" sz="sm" onClick={()=>go("/member")}>Vendor Login</Btn><Btn v="accent" sz="sm" onClick={()=>go("/submit")}>Submit Event</Btn></div><button className="mobtn" onClick={()=>setO(!o)} style={{width:36,height:36,alignItems:"center",justifyContent:"center",fontSize:20}}>{o?"✕":"☰"}</button></div></nav>{o&&<div style={{position:"fixed",top:56,left:0,right:0,bottom:0,background:"var(--bg)",zIndex:99,padding:"24px 20px"}}>{[["Submit an Event","/submit"],["Join as Vendor","/join"],["Verified Access","/access"],["Vendor Login","/member"]].map(([l,p])=><button key={p} onClick={()=>{go(p);setO(false)}} style={{display:"block",width:"100%",padding:"18px 0",fontSize:16,fontWeight:500,color:route===p?"var(--accent)":"var(--ink)",textAlign:"left",borderBottom:"1px solid var(--line)"}}>{l}</button>)}</div>}</>}

function HomePage({go}){return<>
<section className="sp hero-s" style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",padding:"100px 40px 60px",position:"relative",overflow:"hidden"}}><Skyline/><div style={{maxWidth:680,textAlign:"center",position:"relative",zIndex:1}}><div className="au" style={{marginBottom:40}}><p style={{fontSize:12,fontWeight:500,color:"var(--accent)",letterSpacing:".08em",marginBottom:20}}>RICHMOND, VIRGINIA</p><h1 className="hh" style={{fontSize:52,fontWeight:300,color:"var(--ink)",fontFamily:"var(--serif)",lineHeight:1.15,letterSpacing:"-.02em",margin:"0 0 20px"}}>The food truck booking<br/>network for <em style={{fontWeight:400,color:"var(--accent)"}}>Richmond</em>.</h1><p className="sub-t" style={{fontSize:16,color:"var(--sub)",lineHeight:1.7,maxWidth:440,margin:"0 auto",fontWeight:300}}>Submit event requests. Get matched with verified vendors. Book directly — no middlemen, no spam.</p></div><div className="au d1 hc" style={{display:"flex",gap:12,justifyContent:"center"}}><Btn v="accent" sz="lg" onClick={()=>go("/submit")}>Submit an Event</Btn><Btn v="secondary" sz="lg" onClick={()=>go("/join")}>Join as a Vendor</Btn></div><p className="au d2" style={{fontSize:12,color:"var(--mute)",marginTop:20,fontStyle:"italic",fontFamily:"var(--serif)"}}>Serving corporate events, weddings, festivals, and everything in between.</p></div></section>
<div style={{borderTop:"1px solid var(--line)",borderBottom:"1px solid var(--line)",padding:"12px 0",overflow:"hidden"}}><div style={{display:"flex",animation:"ticker 30s linear infinite",whiteSpace:"nowrap"}}>{[0,1,2].map(j=><div key={j} style={{display:"flex"}}>{["BBQ & Smoked Meats","Mexican / Latin","Southern / Soul Food","Asian Fusion","Breakfast & Brunch","Beverages & Dessert","Catering","Weddings","Corporate Events","Festivals"].map((t,i)=><span key={i} style={{padding:"0 28px",fontSize:11,color:"var(--mute)",fontFamily:"var(--mono)"}}>{t}</span>)}</div>)}</div></div>
<section className="sp sec-md" style={{padding:"80px 40px"}}><div style={{maxWidth:1040,margin:"0 auto"}}><div className="au" style={{marginBottom:48}}><p style={{fontSize:12,fontWeight:500,color:"var(--mute)",letterSpacing:".08em",marginBottom:12}}>HOW IT WORKS</p><h2 className="h2m" style={{fontSize:32,fontWeight:300,fontFamily:"var(--serif)",maxWidth:400}}>Simple for hosts.<br/>Valuable for vendors.</h2></div><div className="au d1 g3" style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:1,background:"var(--line)",borderRadius:12,overflow:"hidden"}}>{[["For Event Hosts","Tell us your date, location, headcount, and requirements. We route your request to verified vendors who match.","Submit an Event →","/submit"],["For Vendors","Get listed for free. Receive qualified booking opportunities from hosts across Richmond. Upgrade to Verified for priority.","Join the Network →","/join"],["Direct Booking","No platform fees. No middlemen. Hosts and vendors connect directly. We just make the introduction.","Learn More →","/access"]].map(([t,d,c,l])=><div key={t} className="cp" style={{background:"var(--card)",padding:36}}><h3 style={{fontSize:14,fontWeight:600,marginBottom:10}}>{t}</h3><p style={{fontSize:13,color:"var(--sub)",lineHeight:1.75,marginBottom:20,fontWeight:300}}>{d}</p><span onClick={()=>go(l)} style={{fontSize:13,fontWeight:500,color:"var(--accent)",cursor:"pointer"}}>{c}</span></div>)}</div></div></section>
<div className="sp" style={{padding:"0 40px"}}><div style={{maxWidth:1040,margin:"0 auto",display:"flex",alignItems:"center",gap:16}}><div style={{flex:1,height:1,background:"var(--line)"}}/><span style={{fontSize:10,color:"var(--mute)",fontFamily:"var(--mono)",letterSpacing:".1em"}}>FAFTRVA</span><div style={{flex:1,height:1,background:"var(--line)"}}/></div></div>
<section className="sp sec-sm" style={{padding:"60px 40px"}}><div className="sf" style={{maxWidth:880,margin:"0 auto",display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}><div className="au"><p style={{fontSize:12,fontWeight:500,color:"var(--mute)",letterSpacing:".08em",marginBottom:10}}>CURRENT STATUS</p><h2 style={{fontSize:26,fontWeight:300,fontFamily:"var(--serif)"}}>Now accepting</h2></div><div className="au d1 sf" style={{display:"flex",gap:40}}>{[["Event\nsubmissions","Active"],["Vendor\napplications","Active"],["Verified Vendor\nwaitlist","Open"]].map(([l,s])=><div key={l} style={{textAlign:"right"}}><div style={{display:"flex",alignItems:"center",gap:6,justifyContent:"flex-end",marginBottom:4}}><div style={{width:6,height:6,borderRadius:99,background:s==="Active"?"#2D8C3C":"var(--accent)"}}/><span style={{fontSize:10,fontWeight:500,color:s==="Active"?"#2D8C3C":"var(--accent)",fontFamily:"var(--mono)"}}>{s}</span></div><span style={{fontSize:12,color:"var(--sub)",whiteSpace:"pre-line",lineHeight:1.5}}>{l}</span></div>)}</div></div></section>
<section className="sp dark-s" style={{padding:"80px 40px",background:"var(--ink)",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:"-20%",right:"-5%",width:400,height:400,borderRadius:"50%",background:"radial-gradient(circle,rgba(212,72,44,.06),transparent 60%)",filter:"blur(50px)"}}/><div style={{maxWidth:560,margin:"0 auto",textAlign:"center",position:"relative"}}><p className="au" style={{fontSize:11,fontWeight:500,color:"rgba(255,255,255,.3)",letterSpacing:".08em",marginBottom:14}}>VERIFIED VENDOR ACCESS</p><h2 className="au d1" className="h2m" style={{fontSize:28,fontWeight:300,fontFamily:"var(--serif)",color:"#fff",margin:"0 0 16px"}}>Priority placement. Direct lead access. Category protection.</h2><p className="au d2" style={{fontSize:14,color:"rgba(255,255,255,.4)",lineHeight:1.75,marginBottom:12,fontWeight:300}}>A paid tier for vendors who want first access to booking requests, protected category placement, and featured visibility.</p><p className="au d2" style={{fontSize:13,color:"rgba(255,255,255,.25)",lineHeight:1.7,marginBottom:32,fontStyle:"italic",fontFamily:"var(--serif)"}}>Limited to 1–2 vendors per cuisine category. When your slot is full, your competition is capped.</p><div className="au d3"><Btn v="accent" sz="lg" onClick={()=>go("/access")}>Join the Waitlist</Btn></div></div></section>
<section className="sp sec-sm" style={{padding:"72px 40px",textAlign:"center"}}><div style={{maxWidth:480,margin:"0 auto"}}><h2 className="au" className="h2m" style={{fontSize:26,fontWeight:300,fontFamily:"var(--serif)",margin:"0 0 14px"}}>Richmond’s food truck scene deserves better infrastructure.</h2><p className="au d1" style={{fontSize:14,color:"var(--sub)",lineHeight:1.75,fontWeight:300,marginBottom:28}}>We’re building it. Get in early — whether you’re hosting an event or running a truck.</p><div className="au d2 hc" style={{display:"flex",gap:12,justifyContent:"center"}}><Btn v="accent" onClick={()=>go("/submit")}>Submit an Event</Btn><Btn v="secondary" onClick={()=>go("/join")}>Join as a Vendor</Btn></div></div></section>
<section className="sp sec-sm" style={{padding:"60px 40px",borderTop:"1px solid var(--line)"}}><div className="nm" style={{maxWidth:800,margin:"0 auto",display:"flex",justifyContent:"center",gap:64}}>{[["4,100+","Network members"],["$800–2,500","Avg. booking value"],["10","Verified vendor slots"]].map(([v,l])=><div key={l} style={{textAlign:"center"}}><div style={{fontSize:32,fontWeight:300,fontFamily:"var(--serif)",letterSpacing:"-.02em"}}>{v}</div><div style={{fontSize:11,color:"var(--mute)",marginTop:6,fontFamily:"var(--mono)"}}>{l}</div></div>)}</div></section>
</>}

function SubmitEvent({go}){const[step,setStep]=useState(1);const[f,sF]=useState({type:"",date:"",time:"",location:"",attendance:"",cuisine:"",budget:"",name:"",email:"",phone:"",org:"",notes:""});const u=(k,v)=>sF({...f,[k]:v});const types=["Corporate","Wedding","Private Party","Festival","Community","School / Nonprofit","Other"];
if(step===4)return<section className="sp" style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",padding:"80px 20px"}}><div className="au" style={{textAlign:"center",maxWidth:440,padding:"0 16px"}}><div style={{width:48,height:48,borderRadius:99,background:"var(--accent)",color:"#fff",display:"flex",alignItems:"center",justifyContent:"center",fontSize:20,margin:"0 auto 24px"}}>✓</div><h2 style={{fontSize:24,fontWeight:300,fontFamily:"var(--serif)",margin:"0 0 12px"}}>Request submitted.</h2><p style={{fontSize:15,color:"var(--sub)",lineHeight:1.7,fontWeight:300}}>Verified vendors matching your requirements will be notified. Expect responses within 24 hours.</p><div style={{marginTop:32}}><Btn v="secondary" onClick={()=>go("/")}>Back to home</Btn></div></div></section>;
return<section className="sp" style={{minHeight:"100vh",padding:"80px 16px 60px"}}><div style={{maxWidth:560,margin:"0 auto"}}><div className="au" style={{marginBottom:24}}><span onClick={()=>go("/")} style={{fontSize:13,color:"var(--mute)",cursor:"pointer",display:"inline-block",marginBottom:12}}>← Back</span><h1 style={{fontSize:24,fontWeight:300,fontFamily:"var(--serif)",margin:"0 0 6px"}}>Submit an Event</h1><p style={{fontSize:13,color:"var(--sub)"}}>Step {step} of 3</p></div><div style={{display:"flex",gap:4,marginBottom:32}}>{[1,2,3].map(s=><div key={s} style={{flex:1,height:2,borderRadius:2,background:s<=step?"var(--accent)":"var(--line)"}}/>)}</div><div className="au d1 cp" style={{background:"var(--card)",borderRadius:12,border:"1px solid var(--line)",padding:32}}>
{step===1&&<><h3 style={{fontSize:15,fontWeight:600,marginBottom:20}}>Event Details</h3><div style={{marginBottom:16}}><label style={{display:"block",fontSize:12,fontWeight:500,color:"var(--sub)",marginBottom:8}}>Event Type</label><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{types.map(t=><Chip key={t} active={f.type===t} onClick={()=>u("type",t)}>{t}</Chip>)}</div></div><div className="fc" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"0 16px"}}><Input label="Date" value={f.date} onChange={e=>u("date",e.target.value)} type="date"/><Input label="Time" value={f.time} onChange={e=>u("time",e.target.value)} placeholder="e.g. 4:00 PM – 8:00 PM"/></div><Input label="Location" value={f.location} onChange={e=>u("location",e.target.value)} placeholder="Venue name or address"/><Input label="Expected Attendance" value={f.attendance} onChange={e=>u("attendance",e.target.value)} placeholder="Number of guests" type="number"/><div style={{display:"flex",justifyContent:"flex-end",marginTop:8}}><Btn v="accent" onClick={()=>setStep(2)}>Continue</Btn></div></>}
{step===2&&<><h3 style={{fontSize:15,fontWeight:600,marginBottom:20}}>Requirements</h3><Input label="Cuisine Preferences" value={f.cuisine} onChange={e=>u("cuisine",e.target.value)} placeholder="e.g. BBQ, Mexican, Any"/><Input label="Budget Range" value={f.budget} onChange={e=>u("budget",e.target.value)} placeholder="e.g. $500 – $1,000"/><Input label="Additional Requirements" value={f.notes} onChange={e=>u("notes",e.target.value)} placeholder="Dietary needs, setup requirements..." textarea rows={4}/><div style={{display:"flex",justifyContent:"space-between",marginTop:8}}><Btn v="ghost" onClick={()=>setStep(1)}>Back</Btn><Btn v="accent" onClick={()=>setStep(3)}>Continue</Btn></div></>}
{step===3&&<><h3 style={{fontSize:15,fontWeight:600,marginBottom:20}}>Contact Information</h3><Input label="Your Name" value={f.name} onChange={e=>u("name",e.target.value)} placeholder="Full name"/><Input label="Organization" value={f.org} onChange={e=>u("org",e.target.value)} placeholder="Company or organization (optional)"/><div className="fc" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"0 16px"}}><Input label="Email" value={f.email} onChange={e=>u("email",e.target.value)} placeholder="you@email.com" type="email"/><Input label="Phone" value={f.phone} onChange={e=>u("phone",e.target.value)} placeholder="(804) 555-0000"/></div><div style={{display:"flex",justifyContent:"space-between",marginTop:8}}><Btn v="ghost" onClick={()=>setStep(2)}>Back</Btn><Btn v="accent" onClick={()=>setStep(4)}>Submit Request</Btn></div></>}
</div></div></section>}

function JoinVendor({go}){const[step,setStep]=useState(1);const[f,sF]=useState({truck:"",cuisine:"",owner:"",phone:"",email:"",schedule:"",description:"",waitlist:false});const u=(k,v)=>sF({...f,[k]:v});const cuisines=["BBQ & Smoked","Mexican / Latin","Southern / Soul","Asian Fusion","Breakfast / Brunch","Beverages / Dessert","Other"];
if(step===4)return<section className="sp" style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",padding:"80px 20px"}}><div className="au" style={{textAlign:"center",maxWidth:440,padding:"0 16px"}}><div style={{width:48,height:48,borderRadius:99,background:"var(--accent)",color:"#fff",display:"flex",alignItems:"center",justifyContent:"center",fontSize:20,margin:"0 auto 24px"}}>✓</div><h2 style={{fontSize:24,fontWeight:300,fontFamily:"var(--serif)",margin:"0 0 12px"}}>You’re in the network.</h2><p style={{fontSize:15,color:"var(--sub)",lineHeight:1.7,fontWeight:300}}>Your application is received. Log in to complete your profile and add your menu.</p>{f.waitlist&&<p style={{fontSize:13,fontWeight:500,background:"var(--accentL)",color:"var(--accent)",padding:"10px 16px",borderRadius:8,display:"inline-block",marginTop:12}}>Verified Vendor waitlist — application received.</p>}<div style={{marginTop:32,display:"flex",gap:10,justifyContent:"center"}}><Btn v="accent" onClick={()=>go("/member")}>Set Up Profile</Btn><Btn v="secondary" onClick={()=>go("/")}>Back to home</Btn></div></div></section>;
return<section className="sp" style={{minHeight:"100vh",padding:"80px 16px 60px"}}><div style={{maxWidth:560,margin:"0 auto"}}><div className="au" style={{marginBottom:24}}><span onClick={()=>go("/")} style={{fontSize:13,color:"var(--mute)",cursor:"pointer",display:"inline-block",marginBottom:12}}>← Back</span><h1 style={{fontSize:24,fontWeight:300,fontFamily:"var(--serif)",margin:"0 0 6px"}}>Join as a Vendor</h1><p style={{fontSize:13,color:"var(--sub)"}}>Step {step} of 3 — Free to join</p></div><div style={{display:"flex",gap:4,marginBottom:32}}>{[1,2,3].map(s=><div key={s} style={{flex:1,height:2,borderRadius:2,background:s<=step?"var(--accent)":"var(--line)"}}/>)}</div><div className="au d1 cp" style={{background:"var(--card)",borderRadius:12,border:"1px solid var(--line)",padding:32}}>
{step===1&&<><h3 style={{fontSize:15,fontWeight:600,marginBottom:20}}>Business Information</h3><Input label="Truck Name" value={f.truck} onChange={e=>u("truck",e.target.value)} placeholder="Your food truck name"/><div style={{marginBottom:16}}><label style={{display:"block",fontSize:12,fontWeight:500,color:"var(--sub)",marginBottom:8}}>Primary Cuisine</label><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{cuisines.map(c=><Chip key={c} active={f.cuisine===c} onClick={()=>u("cuisine",c)}>{c}</Chip>)}</div></div><Input label="Typical Schedule" value={f.schedule} onChange={e=>u("schedule",e.target.value)} placeholder="e.g. Tue–Sat 11am–8pm"/><Input label="Brief Description" value={f.description} onChange={e=>u("description",e.target.value)} placeholder="What you serve, your style..." textarea rows={3}/><div style={{display:"flex",justifyContent:"flex-end",marginTop:8}}><Btn v="accent" onClick={()=>setStep(2)}>Continue</Btn></div></>}
{step===2&&<><h3 style={{fontSize:15,fontWeight:600,marginBottom:20}}>Contact</h3><Input label="Owner / Operator Name" value={f.owner} onChange={e=>u("owner",e.target.value)} placeholder="Full name"/><div className="fc" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"0 16px"}}><Input label="Email" value={f.email} onChange={e=>u("email",e.target.value)} placeholder="you@email.com" type="email"/><Input label="Phone" value={f.phone} onChange={e=>u("phone",e.target.value)} placeholder="(804) 555-0000"/></div><div style={{display:"flex",justifyContent:"space-between",marginTop:8}}><Btn v="ghost" onClick={()=>setStep(1)}>Back</Btn><Btn v="accent" onClick={()=>setStep(3)}>Continue</Btn></div></>}
{step===3&&<><h3 style={{fontSize:15,fontWeight:600,marginBottom:20}}>Verified Vendor Access</h3><div style={{background:"var(--tint)",borderRadius:10,padding:20,marginBottom:20,border:"1px solid var(--line)"}}><h4 style={{fontSize:13,fontWeight:600,marginBottom:6}}>Verified Vendor tier — launching soon</h4><p style={{fontSize:12,color:"var(--sub)",lineHeight:1.7,fontWeight:300,marginBottom:12}}>Priority placement, direct lead routing, category protection, and featured visibility.</p><label style={{display:"flex",alignItems:"flex-start",gap:10,cursor:"pointer"}}><input type="checkbox" checked={f.waitlist} onChange={e=>u("waitlist",e.target.checked)} style={{marginTop:3,accentColor:"var(--accent)"}}/><span style={{fontSize:13,lineHeight:1.6}}>Yes, add me to the Verified Vendor waitlist.</span></label></div><div style={{display:"flex",justifyContent:"space-between",marginTop:8}}><Btn v="ghost" onClick={()=>setStep(2)}>Back</Btn><Btn v="accent" onClick={()=>setStep(4)}>Join Network</Btn></div></>}
</div></div></section>}

function AccessPage({go}){const[done,setDone]=useState(false);const[f,sF]=useState({name:"",truck:"",cuisine:"",email:"",why:""});const u=(k,v)=>sF({...f,[k]:v});const cs=["BBQ & Smoked","Mexican / Latin","Southern / Soul","Asian Fusion","Breakfast / Brunch","Beverages / Dessert"];
return<section className="sp" style={{minHeight:"100vh",padding:"80px 16px 60px"}}><div style={{maxWidth:720,margin:"0 auto"}}><div className="au" style={{marginBottom:48}}><span onClick={()=>go("/")} style={{fontSize:13,color:"var(--mute)",cursor:"pointer",display:"inline-block",marginBottom:12}}>← Back</span><h1 style={{fontSize:32,fontWeight:300,fontFamily:"var(--serif)",margin:"0 0 14px"}}>Verified Vendor Access</h1><p style={{fontSize:15,color:"var(--sub)",lineHeight:1.75,fontWeight:300,maxWidth:500}}>A structured tier for vendors who want priority access to booking requests, protected category placement, and featured visibility.</p></div>
<div className="au d1 g2" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:1,background:"var(--line)",borderRadius:12,overflow:"hidden",marginBottom:48}}>{[["Priority Placement","Your profile appears first to event hosts across the network."],["Direct Lead Routing","Booking requests matched to your cuisine sent directly to you."],["Category Protection","Limited slots per cuisine. Your competition is capped."],["Featured Visibility","Prominent placement in directory and event matching."]].map(([t,d])=><div key={t} className="cp" style={{background:"var(--card)",padding:28}}><h3 style={{fontSize:13,fontWeight:600,marginBottom:6}}>{t}</h3><p style={{fontSize:12,color:"var(--sub)",lineHeight:1.7,fontWeight:300}}>{d}</p></div>)}</div>
{!done?<div className="au d2 cp" style={{background:"var(--card)",borderRadius:12,border:"1px solid var(--line)",padding:32}}><h3 style={{fontSize:18,fontWeight:300,fontFamily:"var(--serif)",marginBottom:6}}>Join the waitlist</h3><p style={{fontSize:13,color:"var(--sub)",lineHeight:1.7,fontWeight:300,marginBottom:24}}>Limited availability per cuisine category.</p><div className="fc" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"0 16px"}}><Input label="Your Name" value={f.name} onChange={e=>u("name",e.target.value)} placeholder="Full name"/><Input label="Truck Name" value={f.truck} onChange={e=>u("truck",e.target.value)} placeholder="Your food truck"/></div><Input label="Email" value={f.email} onChange={e=>u("email",e.target.value)} placeholder="you@email.com" type="email"/><div style={{marginBottom:16}}><label style={{display:"block",fontSize:12,fontWeight:500,color:"var(--sub)",marginBottom:8}}>Cuisine Category</label><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{cs.map(c=><Chip key={c} active={f.cuisine===c} onClick={()=>u("cuisine",c)}>{c}</Chip>)}</div></div><Input label="Why are you interested?" value={f.why} onChange={e=>u("why",e.target.value)} placeholder="Tell us about your truck..." textarea rows={3}/><Btn v="accent" full onClick={()=>{if(f.name&&f.truck&&f.email&&f.cuisine)setDone(true)}}>Submit Application</Btn></div>
:<div className="au" style={{textAlign:"center",padding:"48px 20px"}}><div style={{width:48,height:48,borderRadius:99,background:"var(--accent)",color:"#fff",display:"flex",alignItems:"center",justifyContent:"center",fontSize:20,margin:"0 auto 24px"}}>✓</div><h3 style={{fontSize:24,fontWeight:300,fontFamily:"var(--serif)",margin:"0 0 12px"}}>Application received.</h3><p style={{fontSize:14,color:"var(--sub)",lineHeight:1.7,fontWeight:300,maxWidth:380,margin:"0 auto"}}>We’ll review your application and reach out when the verified tier launches.</p><div style={{marginTop:20,fontSize:13,color:"var(--mute)",fontFamily:"var(--mono)"}}>{f.truck} · {f.cuisine}</div></div>}
</div></section>}

function MemberLogin({onLogin}){const[pw,setPw]=useState("");const[e,sE]=useState(false);return<div style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",padding:"80px 20px"}}><div className="au" style={{width:"100%",maxWidth:380,padding:28,borderRadius:12,background:"var(--card)",border:"1px solid var(--line)",textAlign:"center"}}><h2 style={{fontSize:22,fontWeight:300,fontFamily:"var(--serif)",margin:"0 0 6px"}}>Vendor Portal</h2><p style={{fontSize:13,color:"var(--sub)",marginBottom:24,fontWeight:300}}>Manage your profile and menu.</p>{e&&<p style={{color:"#DC2626",fontSize:12,marginBottom:12}}>Invalid password.</p>}<input value={pw} onChange={ev=>setPw(ev.target.value)} onKeyDown={ev=>ev.key==="Enter"&&(onLogin(pw)?0:(sE(true),setPw("")))} type="password" placeholder="Enter password" style={{width:"100%",padding:"12px 16px",borderRadius:8,border:"1px solid var(--line)",fontSize:14,marginBottom:12,textAlign:"center"}}/><Btn v="accent" full onClick={()=>{if(!onLogin(pw)){sE(true);setPw("")}}}>Sign In</Btn></div></div>}

function MemberDash({go}){const[tab,setTab]=useState("profile");const[profile,setProfile]=useState({name:"",cuisine:"",owner:"",phone:"",schedule:"",price:"",desc:""});const[menu,setMenu]=useState([]);const[ni,sNi]=useState({name:"",price:"",desc:""});const[scanning,setScanning]=useState(false);const[scanErr,setScanErr]=useState(null);const[scanPrev,setScanPrev]=useState(null);const fr=useRef(null);const up=(k,v)=>setProfile({...profile,[k]:v});
const scan=async(file)=>{if(!file)return;setScanErr(null);setScanning(true);const r=new FileReader();r.onload=async(ev)=>{const d=ev.target.result;setScanPrev(d);const b=d.split(",")[1];const mt=file.type||"image/jpeg";try{const resp=await fetch("/api/scan-menu",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({base64:b,mediaType:mt})});const data=await resp.json();if(data.items&&data.items.length>0)setMenu(p=>[...p,...data.items]);else setScanErr("Couldn't parse items.")}catch(e){setScanErr("Failed. Try again.")}setScanning(false)};r.readAsDataURL(file)};
return<section className="sp" style={{minHeight:"100vh",padding:"80px 20px 60px"}}><div style={{maxWidth:960,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:32}}><div><h1 style={{fontSize:22,fontWeight:400,fontFamily:"var(--serif)"}}>Vendor Dashboard</h1><p style={{fontSize:13,color:"var(--sub)",marginTop:4}}>Manage your profile, menu, and visibility.</p></div><Btn v="ghost" sz="sm" onClick={()=>go("/")}>← Site</Btn></div>
<div style={{display:"flex",gap:4,marginBottom:28,borderBottom:"1px solid var(--line)"}}>{["profile","menu"].map(t=><button key={t} onClick={()=>setTab(t)} style={{padding:"12px 16px",fontSize:13,fontWeight:500,color:tab===t?"var(--ink)":"var(--mute)",borderBottom:tab===t?"2px solid var(--accent)":"2px solid transparent",textTransform:"capitalize"}}>{t}</button>)}</div>
{tab==="profile"&&<div className="cp" style={{background:"var(--card)",borderRadius:12,border:"1px solid var(--line)",padding:32,maxWidth:560}}><h3 style={{fontSize:15,fontWeight:600,marginBottom:20}}>Truck Profile</h3><Input label="Truck Name" value={profile.name} onChange={e=>up("name",e.target.value)} placeholder="Your truck name"/><div className="fc" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"0 16px"}}><Input label="Cuisine" value={profile.cuisine} onChange={e=>up("cuisine",e.target.value)} placeholder="e.g. BBQ"/><Input label="Price Range" value={profile.price} onChange={e=>up("price",e.target.value)} placeholder="e.g. $$"/></div><div className="fc" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"0 16px"}}><Input label="Owner" value={profile.owner} onChange={e=>up("owner",e.target.value)} placeholder="Your name"/><Input label="Phone" value={profile.phone} onChange={e=>up("phone",e.target.value)} placeholder="(804) 555-0000"/></div><Input label="Schedule" value={profile.schedule} onChange={e=>up("schedule",e.target.value)} placeholder="e.g. Tue–Sat 11am–8pm"/><Input label="Description" value={profile.desc} onChange={e=>up("desc",e.target.value)} placeholder="What makes your truck special..." textarea rows={3}/><Btn v="accent" full>Save Profile</Btn></div>}
{tab==="menu"&&<div style={{maxWidth:640}}><h3 style={{fontSize:15,fontWeight:600,marginBottom:20}}>Menu ({menu.length} items)</h3><div style={{background:"var(--card)",borderRadius:12,border:"1px dashed var(--line)",padding:28,textAlign:"center",marginBottom:20,cursor:"pointer"}} onClick={()=>fr.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const fl=e.dataTransfer.files[0];if(fl)scan(fl)}}><input ref={fr} type="file" accept="image/*" style={{display:"none"}} onChange={e=>{const fl=e.target.files[0];if(fl)scan(fl)}}/>{scanning?<p style={{fontSize:13,color:"var(--sub)"}}>Scanning...</p>:<><p style={{fontSize:14,fontWeight:500,color:"var(--accent)",marginBottom:4}}>Scan menu from photo</p><p style={{fontSize:12,color:"var(--mute)"}}>Drop a photo or click to upload.</p></>}</div>
{scanPrev&&<div style={{marginBottom:16}}><img src={scanPrev} alt="Menu" style={{maxWidth:"100%",borderRadius:8,border:"1px solid var(--line)"}}/></div>}
{scanErr&&<p style={{color:"#DC2626",fontSize:12,marginBottom:16}}>{scanErr}</p>}
{menu.map((m,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"12px 0",borderBottom:"1px solid var(--line)"}}><div><div style={{fontSize:14,fontWeight:500}}>{m.name}</div>{m.desc&&<div style={{fontSize:12,color:"var(--mute)",marginTop:2}}>{m.desc}</div>}</div><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{fontSize:14,fontWeight:600,fontFamily:"var(--mono)"}}>${m.price}</span><button onClick={()=>setMenu(menu.filter((_,j)=>j!==i))} style={{fontSize:11,color:"var(--mute)",padding:"4px 8px",borderRadius:6,border:"1px solid var(--line)"}}>Remove</button></div></div>)}
<div style={{background:"var(--tint)",borderRadius:10,padding:16,marginTop:20}}><p style={{fontSize:11,fontWeight:500,color:"var(--sub)",marginBottom:10}}>ADD MANUALLY</p><div style={{display:"grid",gridTemplateColumns:"1fr 80px",gap:8,marginBottom:8}}><input value={ni.name} onChange={e=>sNi({...ni,name:e.target.value})} placeholder="Item name" style={{padding:"10px 12px",borderRadius:6,border:"1px solid var(--line)",fontSize:13}}/><input value={ni.price} onChange={e=>sNi({...ni,price:e.target.value})} placeholder="$" style={{padding:"10px 12px",borderRadius:6,border:"1px solid var(--line)",fontSize:13}}/></div><input value={ni.desc} onChange={e=>sNi({...ni,desc:e.target.value})} placeholder="Description (optional)" style={{width:"100%",padding:"10px 12px",borderRadius:6,border:"1px solid var(--line)",fontSize:13,marginBottom:10}}/><Btn v="accent" full sz="sm" onClick={()=>{if(ni.name&&ni.price){setMenu([...menu,{name:ni.name,price:Number(ni.price),desc:ni.desc}]);sNi({name:"",price:"",desc:""})}}}>Add Item</Btn></div></div>}
</div></section>}

function AdminLogin({onLogin}){const[pw,setPw]=useState("");const[e,sE]=useState(false);return<div style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",background:"#0A0A0A"}}><div className="au" style={{width:360,maxWidth:"90%",padding:32,borderRadius:12,background:"#141414",border:"1px solid #222",textAlign:"center"}}><h2 style={{fontSize:20,fontWeight:500,color:"#fff",marginBottom:24}}>Admin Access</h2>{e&&<p style={{color:"#EF4444",fontSize:12,marginBottom:12}}>Invalid.</p>}<input value={pw} onChange={ev=>setPw(ev.target.value)} onKeyDown={ev=>ev.key==="Enter"&&(onLogin(pw)?0:(sE(true),setPw("")))} type="password" placeholder="Password" style={{width:"100%",padding:"12px 16px",borderRadius:8,border:"1px solid #333",fontSize:14,background:"#0A0A0A",color:"#fff",marginBottom:12,textAlign:"center"}}/><button onClick={()=>{if(!onLogin(pw)){sE(true);setPw("")}}} style={{width:"100%",padding:12,borderRadius:8,background:"#fff",color:"#000",fontSize:14,fontWeight:500}}>Enter</button></div></div>}
function PinGate({onUnlock,onCancel}){const[pin,setPin]=useState("");const[e,sE]=useState(false);return<div style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",background:"#0A0A0A"}}><div style={{width:320,maxWidth:"90%",textAlign:"center"}}><h2 style={{fontSize:18,fontWeight:500,color:"#fff",marginBottom:24}}>Security PIN</h2>{e&&<p style={{color:"#EF4444",fontSize:12,marginBottom:12}}>Invalid PIN.</p>}<input value={pin} onChange={ev=>setPin(ev.target.value)} onKeyDown={ev=>ev.key==="Enter"&&(pin===SP?onUnlock():(sE(true),setPin("")))} type="password" maxLength={4} placeholder="••••" style={{width:"100%",padding:14,borderRadius:8,border:"1px solid #333",fontSize:24,letterSpacing:12,background:"#0A0A0A",color:"#fff",textAlign:"center",marginBottom:16}}/><div style={{display:"flex",gap:8}}><button onClick={onCancel} style={{flex:1,padding:12,borderRadius:8,border:"1px solid #333",color:"#666",fontSize:13}}>Cancel</button><button onClick={()=>{pin===SP?onUnlock():(sE(true),setPin(""))}} style={{flex:1,padding:12,borderRadius:8,background:"#fff",color:"#000",fontSize:13,fontWeight:500}}>Unlock</button></div></div></div>}
function AdminDash({go}){return<div style={{minHeight:"100vh",background:"#0A0A0A",padding:"40px 20px",color:"#fff"}}><div style={{maxWidth:960,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:40}}><h1 style={{fontSize:20,fontWeight:500}}>FAFTRVA Admin</h1><button onClick={()=>go("/")} style={{color:"#666",fontSize:13,border:"1px solid #333",padding:"8px 16px",borderRadius:8}}>← Site</button></div><div className="g3" style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:16,marginBottom:40}}>{[["Event Submissions","0","Pending"],["Vendor Applications","0","Pending"],["Waitlist","0","Applications"]].map(([t,v,l])=><div key={t} style={{background:"#141414",borderRadius:10,padding:20,border:"1px solid #222"}}><div style={{fontSize:11,color:"#666",marginBottom:8,fontFamily:"var(--mono)"}}>{t}</div><div style={{fontSize:28,fontWeight:300}}>{v}</div><div style={{fontSize:11,color:"#444",marginTop:4}}>{l}</div></div>)}</div><p style={{color:"#444",fontSize:13}}>Dashboard populates as submissions arrive.</p></div></div>}

function Footer({go}){return<footer style={{borderTop:"1px solid var(--line)",padding:"40px 20px 28px"}}><div className="fg" style={{maxWidth:1120,margin:"0 auto",display:"grid",gridTemplateColumns:"2fr 1fr 1fr 1fr",gap:40}}><div><div style={{display:"flex",alignItems:"baseline",gap:5}}><span style={{fontFamily:"var(--serif)",fontSize:16,fontStyle:"italic"}}>find a</span><span style={{fontFamily:"var(--serif)",fontSize:16,fontWeight:500,color:"var(--accent)"}}>food truck</span></div><p style={{fontSize:12,color:"var(--sub)",marginTop:8,lineHeight:1.7,fontWeight:300,maxWidth:240}}>Richmond’s structured booking network for food trucks and event organizers.</p><p style={{fontSize:10,color:"var(--mute)",marginTop:10,fontFamily:"var(--mono)"}}>Built by Laurence Ash LLC</p></div>{[["Network",[["Submit Event","/submit"],["Join as Vendor","/join"],["Verified Access","/access"]]],["Account",[["Vendor Login","/member"],["Admin","/admin"]]],["Info",[["Contact","#"],["Terms","#"]]]].map(([t,items])=><div key={t}><h4 style={{fontSize:10,fontWeight:500,color:"var(--mute)",letterSpacing:".08em",marginBottom:12}}>{t.toUpperCase()}</h4>{items.map(([l,to])=><div key={l} onClick={()=>to.startsWith("/")?go(to):null} style={{color:"var(--sub)",fontSize:12,cursor:to.startsWith("/")?"pointer":"default",padding:"3px 0",fontWeight:300}}>{l}</div>)}</div>)}</div><div style={{maxWidth:1120,margin:"24px auto 0",paddingTop:14,borderTop:"1px solid var(--line)",display:"flex",justifyContent:"space-between"}}><span style={{color:"var(--mute)",fontSize:10,fontFamily:"var(--mono)"}}>© 2026 FAFTRVA</span><span style={{color:"var(--mute)",fontSize:10}}>Richmond, VA</span></div></footer>}

export default function App(){const{route,go}=useRouter();const[m,sM]=useState(false);const[a,sA]=useState(false);const[p,sP]=useState(false);
if(route==="/member"){if(!m)return<><style>{G}</style><MemberLogin onLogin={pw=>{if(pw===MP){sM(true);return true}return false}}/></>;return<><style>{G}</style><MemberDash go={go}/></>}
if(route==="/admin"){if(!a)return<><style>{G}</style><AdminLogin onLogin={pw=>{if(pw===AP){sA(true);return true}return false}}/></>;if(!p)return<><style>{G}</style><PinGate onUnlock={()=>sP(true)} onCancel={()=>{sA(false);go("/")}}/></>;return<><style>{G}</style><AdminDash go={go}/></>}
return<div style={{background:"var(--bg)",minHeight:"100vh"}}><style>{G}</style><Nav go={go} route={route}/>
{route==="/"&&<><HomePage go={go}/><Footer go={go}/></>}
{route==="/submit"&&<><SubmitEvent go={go}/><Footer go={go}/></>}
{route==="/join"&&<><JoinVendor go={go}/><Footer go={go}/></>}
{route==="/access"&&<><AccessPage go={go}/><Footer go={go}/></>}
</div>}
